# -*- coding: utf-8 -*-
"""question1lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h_XmUK8WFro94H5CoSCXvRb_Ce4b6y_x

## Setup PySpark
"""

import findspark
findspark.init()
from pyspark.sql import SparkSession


spark = SparkSession.builder.appName("TipsData").getOrCreate()

tips_df = spark.read.csv('/content/tips.csv', header=True, inferSchema=True)

print("DataFrame Schema:")
tips_df.printSchema()

print("\nFirst 10 records of the DataFrame:")
tips_df.show(10)

from pyspark.sql.functions import round

tips_df = tips_df.withColumn(
    "Tip_Percentage",
    round((tips_df['tip'] / tips_df['total_bill']) * 100, 2)
)

print("DataFrame with 'Tip_Percentage' column:")
tips_df.show(10)

tips_df.createOrReplaceTempView("tips")

"""## Spark SQL Queries"""

# 1. Find the average total bill for each day
print("Average total bill for each day:")
avg_bill_per_day = spark.sql("SELECT day, AVG(total_bill) as Average_Total_Bill FROM tips GROUP BY day ORDER BY Average_Total_Bill DESC")
display(avg_bill_per_day)
avg_bill_per_day.show()

# 2. Find the maximum tip given by gender
print("\nMaximum tip given by gender:")
max_tip_by_gender = spark.sql("SELECT gender, MAX(tip) as Max_Tip FROM tips GROUP BY gender")
display(max_tip_by_gender)
max_tip_by_gender.show()

# 3. Display all records where tip percentage is greater than 20%
print("\nRecords where Tip_Percentage is greater than 20%:")
tips_gt_20_percent = spark.sql("SELECT * FROM tips WHERE Tip_Percentage > 20 ORDER BY Tip_Percentage DESC")
display(tips_gt_20_percent)
tips_gt_20_percent.show()

from pyarrow.ipc import pa
tips_gt_20_percent.write.parquet("tips_gt_20_percent.parquet")

